torchrun --nproc_per_node=1 --master_port=9778 train/stage_1_sft.py \
    --model_name_or_path hugging-quants/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4 \
    --lora_r 16 \
    --lora_alpha 32 \
    --lora_dropout 0.05 \
    --data_path ./data/sft_train/train.pkl \
    --bf16 True \
    --fp16 False \
    --output_dir ./models/stage_1_helpfulsumm_ft_2 \
    --num_train_epochs 2 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --save_strategy "epoch" \
    --learning_rate 2e-6 \
    --weight_decay 0 \
    --warmup_ratio 0 \
    --warmup_steps 0 \
    --lr_scheduler_type "cosine" \
    --logging_steps 5 \
    --model_max_length 32768 \
    --q_lora False \
    --gradient_checkpointing True \
    --report_to "none" \
    --seed 42 \
    --optim "paged_adamw_32bit" \
    --ddp_find_unused_parameters False